apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-java-back
  namespace: api-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-java
  template:
    metadata:
      labels:
        app: api-java
    spec:
      containers:
        - name: api-java
          image: votre_registry/backend:tag
          ports:
            - containerPort: 8082
